# write me
language: python

dist: bionic
sudo: required

env:
  global:
    - ROUTEROS_VERSION=6.45.8
  # 6.43.4 
  # matrix:
  #   - USE_NETWORK=true
  #   - USE_NETWORK=false

matrix:
  include:
    - os: linux
      python: 3.3
    - os: osx
      python: 3.3

before_install:
  - tests/travis.install.sh

install: 
  - pip install -r tests/requirements.txt

before_script:
  - tests/run_server.sh

script:
  # Check the role/playbook's syntax.
  # - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/routeros.yml --syntax-check
  # install
  - ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/routeros.yml --tags install -vvvv
  # shutdown 
  - ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory.secure tests/routeros.yml --tags shutdown -vvvv
  # lint
  - ansible-lint tests/routeros.yml || true

after_script:
  - killall qemu-system-x86_64 && false